FROM ubuntu:20.04

WORKDIR /workspace

# Install necessary packages
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    curl \
    git \
    wget \
    vim \
    gcc && \
    rm -rf /var/lib/apt/lists/*

# Install VSCode
RUN curl -fsSL https://code-server.dev/install.sh | sh

RUN echo "root:root" | chpasswd

RUN mkdir -p ~/.config/code-server && \
    echo "password: root" > ~/.config/code-server/config.yaml && \
    sed -i 's|password:.*|password: root|g' ~/.config/code-server/config.yaml

EXPOSE 8080

RUN git clone https://github.com/SagiK-Repository/C_Sharp_Deep_Learn.git /workspace

CMD code-server --bind-addr 0.0.0.0:8080 .